"""Initial migration

Revision ID: 0f59f4d5d25a
Revises: 
Create Date: 2023-12-07 15:04:14.839819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f59f4d5d25a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('FIO', sa.String(), nullable=False),
    sa.Column('mark', sa.Enum('UNSATISFACTORY', 'SATISFACTORY', 'GOOD', 'EXCELLENT', name='marks'), nullable=True),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
