global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'attendance_service'
    static_configs:
      - targets: ['attendance_service:80']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']